#IfWinActive, SQL Server Management Studio
	::absolute::ABSOLUTE
	::action::ACTION
	::ada::ADA
	::add::ADD
	::all::ALL
	::allocate::ALLOCATE
	::alter::ALTER
	::and::AND
	::any::ANY
	::are::ARE
	::as::AS
	::asc::ASC
	::assertion::ASSERTION
	::at::AT
	::authorization::AUTHORIZATION
	::avg::AVG
	::backup::BACKUP
	::begin::BEGIN
	::between::BETWEEN
	::bit::BIT
	::bit_length::BIT_LENGTH
	::both::BOTH
	::break::BREAK
	::browse::BROWSE
	::bulk::BULK
	::by::BY
	::cascade::CASCADE
	::cascaded::CASCADED
	::case::CASE
	::cast::CAST
	::catalog::CATALOG
	::char::CHAR
	::char_length::CHAR_LENGTH
	::character::CHARACTER
	::character_length::CHARACTER_LENGTH
	::check::CHECK
	::checkpoint::CHECKPOINT
	::close::CLOSE
	::clustered::CLUSTERED
	::coalesce::COALESCE
	::collate::COLLATE
	::collation::COLLATION
	::column::COLUMN
	::commit::COMMIT
	::compute::COMPUTE
	::connect::CONNECT
	::connection::CONNECTION
	::constraint::CONSTRAINT
	::constraints::CONSTRAINTS
	::contains::CONTAINS
	::containstable::CONTAINSTABLE
	::continue::CONTINUE
	::convert::CONVERT
	::corresponding::CORRESPONDING
	::count::COUNT
	::create::CREATE
	::cross::CROSS
	::current::CURRENT
	::current_date::CURRENT_DATE
	::current_time::CURRENT_TIME
	::current_timestamp::CURRENT_TIMESTAMP
	::current_user::CURRENT_USER
	::cursor::CURSOR
	::database::DATABASE
	::date::DATE
	::datetime::DATETIME
	::day::DAY
	::dbcc::DBCC
	::deallocate::DEALLOCATE
	::dec::DEC
	::decimal::DECIMAL
	::declare::DECLARE
	::default::DEFAULT
	::deferrable::DEFERRABLE
	::deferred::DEFERRED
	::delete::DELETE
	::deny::DENY
	::desc::DESC
	::describe::DESCRIBE
	::descriptor::DESCRIPTOR
	::diagnostics::DIAGNOSTICS
	::disconnect::DISCONNECT
	::disk::DISK
	::distinct::DISTINCT
	::distributed::DISTRIBUTED
	::domain::DOMAIN
	::double::DOUBLE
	::drop::DROP
	::dummy::DUMMY
	::dump::DUMP
	::else::ELSE
	::end-exec::END-EXEC
	::end::END
	::errlvl::ERRLVL
	::escape::ESCAPE
	::except::EXCEPT
	::exception::EXCEPTION
	::exec::EXEC
	::execute::EXECUTE
	::exists::EXISTS
	::exit::EXIT
	::external::EXTERNAL
	::extract::EXTRACT
	::false::FALSE
	::fetch::FETCH
	::file::FILE
	::fillfactor::FILLFACTOR
	::first::FIRST
	::float::FLOAT
	::for::FOR
	::foreign::FOREIGN
	::fortran::FORTRAN
	::found::FOUND
	::freetext::FREETEXT
	::freetexttable::FREETEXTTABLE
	::from::FROM
	::full::FULL
	::function::FUNCTION
	::get::GET
	::global::GLOBAL
	::go::GO
	::goto::GOTO
	::grant::GRANT
	::group::GROUP
	::having::HAVING
	::holdlock::HOLDLOCK
	::hour::HOUR
	::identity::IDENTITY
	::identity_insert::IDENTITY_INSERT
	::identitycol::IDENTITYCOL
	::if::IF
	::immediate::IMMEDIATE
	::in::IN
	::include::INCLUDE
	::index::INDEX
	::indicator::INDICATOR
	::initially::INITIALLY
	::inner::INNER
	::input::INPUT
	::insensitive::INSENSITIVE
	::insert::INSERT
	::int::INT
	::integer::INTEGER
	::intersect::INTERSECT
	::interval::INTERVAL
	::into::INTO
	::is::IS
	::isolation::ISOLATION
	::join::JOIN
	::key::KEY
	::kill::KILL
	::language::LANGUAGE
	::last::LAST
	::leading::LEADING
	::left::LEFT
	::level::LEVEL
	::like::LIKE
	::lineno::LINENO
	::load::LOAD
	::local::LOCAL
	::lower::LOWER
	::match::MATCH
	::max::MAX
	::min::MIN
	::minute::MINUTE
	::module::MODULE
	::month::MONTH
	::names::NAMES
	::national::NATIONAL
	::natural::NATURAL
	::nchar::NCHAR
	::next::NEXT
	::no::NO
	::nocheck::NOCHECK
	::nonclustered::NONCLUSTERED
	::none::NONE
	::not::NOT
	::null::NULL
	::nullif::NULLIF
	::numeric::NUMERIC
	::nvarchar::nvarchar
	::octet_length::OCTET_LENGTH
	::of::OF
	::off::OFF
	::offsets::OFFSETS
	::on::ON
	::only::ONLY
	::open::OPEN
	::opendatasource::OPENDATASOURCE
	::openquery::OPENQUERY
	::openrowset::OPENROWSET
	::openxml::OPENXML
	::option::OPTION
	::or::OR
	::order::ORDER
	::outer::OUTER
	::output::OUTPUT
	::over::OVER
	::overlaps::OVERLAPS
	::pad::PAD
	::partial::PARTIAL
	::pascal::PASCAL
	::percent::PERCENT
	::plan::PLAN
	::position::POSITION
	::precision::PRECISION
	::prepare::PREPARE
	::preserve::PRESERVE
	::primary::PRIMARY
	::print::PRINT
	::prior::PRIOR
	::privileges::PRIVILEGES
	::proc::PROC
	::procedure::PROCEDURE
	::public::PUBLIC
	::raiserror::RAISERROR
	::read::READ
	::readtext::READTEXT
	::real::REAL
	::reconfigure::RECONFIGURE
	::references::REFERENCES
	::relative::RELATIVE
	::replication::REPLICATION
	::restore::RESTORE
	::restrict::RESTRICT
	::return::RETURN
	::revoke::REVOKE
	::right::RIGHT
	::rollback::ROLLBACK
	::rowcount::ROWCOUNT
	::rowguidcol::ROWGUIDCOL
	::rows::ROWS
	::rule::RULE
	::save::SAVE
	::schema::SCHEMA
	::scroll::SCROLL
	::second::SECOND
	::section::SECTION
	::select::SELECT
	::session::SESSION
	::session_user::SESSION_USER
	::set::SET
	::setuser::SETUSER
	::shutdown::SHUTDOWN
	::size::SIZE
	::smallint::SMALLINT
	::some::SOME
	::space::SPACE
	::sql::SQL
	::sqlca::SQLCA
	::sqlcode::SQLCODE
	::sqlerror::SQLERROR
	::sqlstate::SQLSTATE
	::sqlwarning::SQLWARNING
	::statistics::STATISTICS
	::substring::SUBSTRING
	::sum::SUM
	::system_user::SYSTEM_USER
	::table::TABLE
	::temporary::TEMPORARY
	::textsize::TEXTSIZE
	::then::THEN
	::time::TIME
	::timestamp::TIMESTAMP
	::timezone_hour::TIMEZONE_HOUR
	::timezone_minute::TIMEZONE_MINUTE
	::to::TO
	::top::TOP
	::trailing::TRAILING
	::tran::TRAN
	::transaction::TRANSACTION
	::translate::TRANSLATE
	::translation::TRANSLATION
	::trigger::TRIGGER
	::trim::TRIM
	::true::TRUE
	::truncate::TRUNCATE
	::tsequal::TSEQUAL
	::union::UNION
	::unique::UNIQUE
	::unknown::UNKNOWN
	::update::UPDATE
	::updatetext::UPDATETEXT
	::upper::UPPER
	::usage::USAGE
	::use::USE
	::user::USER
	::using::USING
	::value::VALUE
	::values::VALUES
	::varchar::VARCHAR
	::varying::VARYING
	::view::VIEW
	::waitfor::WAITFOR
	::when::WHEN
	::whenever::WHENEVER
	::where::WHERE
	::while::WHILE
	::with::WITH
	::work::WORK
	::write::WRITE
	::writetext::WRITETEXT
	::year::YEAR
	::zone::ZONE
#IfWinActive